#!/usr/bin/env node
// Generated by LiveScript 1.6.0
var fs, jsYaml, yargs, argv, format, indent, json;
fs = require("fs-extra");
jsYaml = require('js-yaml');
yargs = require('yargs');
argv = yargs.option('input', {
  alias: 'i',
  description: 'indicating the input file instead of using stdin',
  type: 'string'
}).option('indent', {
  alias: 't',
  description: 'amount of indentation. default 2',
  type: 'number'
}).option('format', {
  alias: 'f',
  description: 'output format. either `json` or `yaml`. default `json`.',
  type: 'string'
}).help('help').alias('help', 'h').check(function(argv){
  var ref$;
  if (argv.f != null && !((ref$ = argv.f) === 'json' || ref$ === 'yaml')) {
    throw new Error("format " + argv.f + " not recognized.");
  }
  if (argv.t != null && isNaN(argv.t)) {
    throw new Error("indentation should be a number, if provided.");
  }
  return true;
}).argv;
format = argv.f || 'json';
indent = argv.t != null ? +argv.t : 2;
json = JSON.parse(fs.readFileSync(argv.i || 0).toString());
if (format === 'json') {
  console.log(JSON.stringify(json, null, repeatString$(' ', indent)));
} else {
  console.log(jsYaml.dump(json, {
    indent: indent
  }));
}
function repeatString$(str, n){
  for (var r = ''; n > 0; (n >>= 1) && (str += str)) if (n & 1) r += str;
  return r;
}
